### ISSUE TITLE
Gridded baselines with thermal noise

### ISSUE THREAD

**Issue by BellaNasirudin** [BellaNasirudin/py21cmmc_fg#16]
As of now, in likelihood, if we do not have foregrounds, the covariance/variance is calculated by using 0.15*P_signal**2, is that right? 

So won't this mean that we're assuming that Var(Tsys) is also 0.15*noise**2 since it has been added to the signal? Shouldn't Tsys be simulated say 50 times to find the variance?

**Comment by steven-murray** [comment]
You're right. We're not actually using the thermal noise in the likelihood at the moment. We shouldn't need to do simulations to find it though, we should be able to generate it just from the weighting function of the gridding. Nevertheless, *if* a Foreground core is loaded, it's probably just as easy to do it numerically, since the core has to be run many times anyway. 

You can figure out the thermal noise on a (u, eta) pixel by calculating the weighted number of baselines contributing to it. The total variance of the pixel is the variance of a single baseline (it's thermal variance), divided by the number of baselines contributing. Of course, you have to remember that if the baselines are added with different weights, this needs to be taken into account.

**Comment by BellaNasirudin** [comment]
Since we are actually just using the grid centres, there will be no weighting function so I don't quite understand how this works?

**Comment by steven-murray** [comment]
Yes we are using the grid centers for testing, but we are still treating
them as "baselines" so we calculate a weight function. This is all
implemented in the latest commit of mine. Let me know if you think I got it
wrong!

**Comment by steven-murray** [comment]
thermal variance added to the likelihood in 0c1e69c2adca54776b9740e9094977e6430ff0e6
